services:
  web:
    build: .
    container_name: flask_app
    command: /entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
